In [37]:
import numpy as np
import matplotlib.pyplot as plt
from astropy.io import fits
from astropy.wcs import WCS


In [38]:
LINUX_DIRECTORY = "/home/aimee/mphys"
FIGURE_SAVEDIR = "figures/comap_maps"
COORD_FILE_NAME = "/home/aimee/mphys/data/wolf_rayet_coords.reg"
MAPS_DIR = "/home/aimee/mphys/data/comap_maps"
MAPS_FNAMES = [
    "comap_160625_band00_band00_feed01-02-03-04-05-06-07-08-09-11-12-13-14-15-16-17-18-19.fits",
    "comap_160625_band01_band01_feed01-02-03-04-05-06-07-08-09-11-12-13-14-15-16-17-18-19.fits",
    "comap_160625_band02_band02_feed01-02-03-04-05-06-07-08-09-11-12-13-14-15-16-17-18-19.fits",
    "comap_160625_band03_band03_feed01-02-03-04-05-06-07-08-09-11-12-13-14-15-16-17-18-19.fits",
    "comap_160625_band04_band04_feed01-02-03-04-05-06-07-08-09-11-12-13-14-15-16-17-18-19.fits",
    "comap_160625_band05_band05_feed01-02-03-04-05-06-07-08-09-11-12-13-14-15-16-17-18-19.fits",
    "comap_160625_band06_band06_feed01-02-03-04-05-06-07-08-09-11-12-13-14-15-16-17-18-19.fits",
    "comap_160625_band07_band07_feed01-02-03-04-05-06-07-08-09-11-12-13-14-15-16-17-18-19.fits"
]


In [39]:
def read_region(region, map):
    """
    Reads fits data within a region and outputs sum of fluxes within region
    and number of pixels in region. As far as I can tell, this is exactly
    how ds9 does it, if not then it seems to give the exact result anyways.
    """
    REGION_RADIUS = region[2]
    included_pixels = np.array([])
    # print(int(region[0] - region[2]))
    x_lbound = int(np.round(region[0]-1 - REGION_RADIUS))
    x_ubound = int(np.round(region[0] + REGION_RADIUS))
    y_lbound = int(np.round(region[1]-1 - REGION_RADIUS))
    y_ubound = int(np.round(region[1] + REGION_RADIUS))
    for x_pixel in range(x_lbound,x_ubound):
        for y_pixel in range(y_lbound,y_ubound):
            pixel_distance = np.sqrt(
                                     (region[0]-1 - x_pixel)**2 +
                                     (region[1]-1 - y_pixel)**2
                                     )
            if pixel_distance <= REGION_RADIUS:
                included_pixels = np.append(included_pixels,
                                            map[y_pixel, x_pixel])
    
    region_info = [np.sum(included_pixels), len(included_pixels)]


    return region_info

In [66]:

# MAIN CODE
with open(COORD_FILE_NAME, 'r') as file:
    lines = file.readlines()
reg_data = [line.strip().split() for line in lines]
reg_data = np.delete(reg_data, 0, axis=1).astype('float') # remove 'galactic;circle' column - just l, b, radius
# print(len(reg_data))
# print(reg_data)

map_fname = MAPS_FNAMES[0] # TEMP - loop through all files later
for region in reg_data:
    print(region)
    region_info = read_region(region, f'{MAPS_DIR}/{map_fname}')
    # print(region_info)


[18.3975      0.9448      0.08333333]
[17.96061     0.17783     0.08333333]
[18.006       0.1818      0.08333333]
[17.5384     -0.1257      0.08333333]
[19.0332      0.5939      0.08333333]
[19.31442     0.40182     0.08333333]
[20.5357      0.9827      0.08333333]
[16.9772     -1.0337      0.08333333]


TypeError: string indices must be integers, not 'tuple'